version: "3"
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    # command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/var/www/remote-work-space
      - public-data:/var/www/remote-work-space/public
      - tmp-data:/var/www/remote-work-space/tmp
      - log-data:/var/www/remote-work-space/log
  #   depends_on:
  #     - db
  # db:
  #   image: mysql:5.7
  #   env_file:
  #     - ./environments/db.env
  #   volumes:
  #     - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/var/www/remote-work-space/public
      - tmp-data:/var/www/remote-work-space/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
